name: Build and test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    env:
      MalievWorkspaceRoot: ${{ github.workspace }}/.dependencies
    steps:
      - name: Check out Web
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - name: Check out Maliev.Aspire
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          repository: MALIEV-Co-Ltd/Maliev.Aspire
          ref: 085f24b8b6b19c5a8e932b229d93421b03bcd032
          path: .dependencies/Maliev.Aspire
          persist-credentials: false
      - name: Check out Maliev.MessagingContracts
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          repository: MALIEV-Co-Ltd/Maliev.MessagingContracts
          ref: c533c12a8154f5cf7c4fbc9734e82a62705ac60f
          path: .dependencies/Maliev.MessagingContracts
          persist-credentials: false
      - name: Validate .NET solution
        uses: MALIEV-Co-Ltd/Legacy.Maliev.Workflows/actions/dotnet-validate@6017816fa67f369d785ed30794f002cfd6299af7
        with:
          solution: Legacy.Maliev.Web.slnx
          use-local-maliev-dependencies: 'true'
